name: "ci"
on:
  pull_request:
  push:
    branches:
      - master
      - dev
jobs:
  compile-lib:
    name: Build the library and upload it to artifacts
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: alpine
            version: 3.13
          - name: ubuntu
            version: 18.04
        compiler: [ gcc, clang ]
        compiler_version: [ 10 ]
    steps:
      - uses: actions/checkout@v2
      - name: Download Base Library
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          workflow: ci.yml
          branch: dev
          name: xalwart.base-${{ matrix.os.name }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}
          repo: YuriyLisovskiy/xalwart.base
      - name: Build the Library
        run: |
          ls xalwart.base-${{ matrix.os.name }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}
          sudo docker run -i \
                          -v ${{ github.workspace }}:/app \
                          xalwart/${{ matrix.compiler }}:${{ matrix.compiler_version }}-${{ matrix.os.name }}-${{ matrix.os.version }} \
                          bash /app/scripts/linux/build.sh ${{ matrix.os.name }} ${{ matrix.compiler }} ${{ matrix.compiler_version }}
      - name: Upload the Artifact
        uses: actions/upload-artifact@v2
        with:
          name: xalwart.server-${{ matrix.os.name }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}
          path: xalwart.server-${{ matrix.os.name }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}
          retention-days: 90
