name: "release"
on:
  workflow_run:
    workflows:
      - "ci"
    branches:
      - release
    types:
      - completed
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Update the Version
        id: bump2version
        run: |
          git config --local user.email "yuralisovskiy98@gmail.com"
          git config --local user.name "YuriyLisovskiy"
          pip install bump2version
          set -x
          bump2version $(bash ./scripts/commit_msg_to_version.sh)
          echo ::set-output name=lib_version::$(cat VERSION)
      - name: Push the Commit
        run: |
          git push
      - name: Create Release
        uses: aaiezza/create-release@master
        with:
          release_branch: master
          tag: v${{ steps.bump2version.outputs.lib_version }}
          name: v${{ steps.bump2version.outputs.lib_version }}
          message: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
