name: "ubuntu-clang"
on:
  push:
    branches:
      - 'dev'
      - '!master'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    name: ${{ matrix.os }} [clang-${{ matrix.compiler_version }}]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [Ubuntu]
        os: [ubuntu-18.04]
        compiler_version: [10]
    env:
      BUILD_TYPE: 'Debug'
    steps:
      - uses: actions/checkout@v2
      - name: Install Compiler and Check Version
        run: |
          sudo apt update -y && \
          sudo pip install --upgrade cmake && \
          sudo apt install -y clang-${{ matrix.compiler_version }} valgrind
      - name: Build and Install Google Test Framework
        run: |
          git clone -q https://github.com/google/googletest.git && \
          sudo mkdir -p ./googletest/build && \
          cd ./googletest/build && \
          sudo cmake -DCMAKE_CXX_COMPILER=clang++-${{ matrix.compiler_version }} \
                     -DCMAKE_C_COMPILER=clang-${{ matrix.compiler_version }} .. && \
          sudo make && \
          sudo make install
      - name: Install Core Library
        run: |
          cd /tmp && \
          git clone https://${{secrets.GH_ACCESS_TOKEN}}@github.com/YuriyLisovskiy/xalwart.core.git && \
          cd xalwart.core && \
          git checkout dev && \
          sudo mkdir build && \
          cd build && \
          sudo cmake -DCMAKE_BUILD_TYPE=Release \
                     -DCMAKE_CXX_COMPILER=clang++-${{ matrix.compiler_version }} \
                     -DCMAKE_C_COMPILER=clang-${{ matrix.compiler_version }} \
                     .. && \
          sudo make && \
          sudo make install
      - name: Update Links and Cache of Linker
        run: |
          sudo ldconfig
      - name: Build Tests
        run: |
          sudo mkdir build && \
          cd build/ && \
          sudo cmake -DCMAKE_TEST_ALL_ONLY=yes \
                     -DCMAKE_CXX_COMPILER=clang++-${{ matrix.compiler_version }} \
                     -DCMAKE_C_COMPILER=clang-${{ matrix.compiler_version }} \
                     -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
                     .. && \
          sudo make
      - name: Run Tests
        run: |
          sudo valgrind --leak-check=full ./build/tests/unittests-all
